### ISSUE TITLE
Dropzone doesn’t work on IE, shows obj error.

### ISSUE THREAD

**Issue by yksingh1097** [rowanwins/vue-dropzone#449]
Hi,
I was working with Dropzone and found that it doesn’t work on Internet Explorer(IE).
I have installed vue2-dropzone version 3.5.9 and on running it on IE (version 11.192.16299.0), it shows the following error:

`[object Error]
SyntaxError: Expected ':'
   
{
  [functions]: ,
  __proto__: { },
  description: "Expected ':'",
  message: "Expected ':'",
  name: "SyntaxError",
  number: -2146827285,
  stack: "SyntaxError: Expected ':'
  at ./node_modules/vue2-dropzone/dist/vue2Dropzone.js (http://localhost:8080/47.js:10:1)
  at __webpack_require__ (http://localhost:8080/app.js:767:12)
  at fn (http://localhost:8080/app.js:130:13)
  at eval code (eval code:2:22)
  at ./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/Widgets/Dropzone.vue?vue&type=script&lang=js& (http://localhost:8080/9.js:11:1)
  at __webpack_require__ (http://localhost:8080/app.js:767:12)
  at fn (http://localhost:8080/app.js:130:13)
  at eval code (eval code:2:22)
  at ./src/components/Widgets/Dropzone.vue?vue&type=script&lang=js& (http://localhost:8080/9.js:71:1)
  at __webpack_require__ (http://localhost:8080/app.js:767:12)",
    Symbol()_m.5oe50ldzm01: undefined,
    Symbol()_n.5oe50ldzm01: undefined,
    Symbol()_o.5oe50ldzm01: undefined,
    Symbol()_p.5oe50ldzm01: undefined,
    Symbol()_q.5oe50ldzm01: undefined,
    Symbol()_u.5oe50ldzm01: undefined,
    Symbol(foo)_v.5oe50ldzm01: undefined,
    Symbol(Symbol.dispose)_s.5oe50ldzm01: undefined,
    Symbol(Symbol.patternMatch)_t.5oe50ldzm01: undefined,
    Symbol(test)_r.5oe50ldzm01: undefined
}`

Thanks in advance. Any kind of help to resolve this issue is appreciable.

**Comment by rowanwins** [comment]
Try dropping back to version `3.5.2`, there are some know IE compatibility problems (outlined in #439 , #443) with the current release.
